### ISSUE TITLE
botocore DataNotFoundError exception

### ISSUE THREAD

**Issue by ghost** [garnaat/petard#2]
I get the following error when trying to create a client instance:

```
...
  File "/Users/andrew/Development/Git/mobile-cloud/eeeeee/lib/python2.7/site-packages/botocore/loaders.py", line 309, in list_api_versions
    raise DataNotFoundError(data_path=service_name)
botocore.exceptions.DataNotFoundError: Unable to load data for: apigateway
```

I installed petard directly with `pip install git+https://github.com/garnaat/petard.git` since it's not in pip yet. Same problem with the setup.py method.

**Comment by garnaat** [comment]
Ok, checking now. Thanks for the report.

**Comment by crankit** [comment]
Same thing, any ideas?

**Comment by garnaat** [comment]
I think I found the problem and fixed it in https://github.com/garnaat/petard/commit/cf7974f9bc7082717361f60f7845ee5ceb370091

**Comment by crankit** [comment]
Thank you! Worked.
